DROP TABLE Disco CASCADE CONSTRAINTS;
DROP TABLE Artists CASCADE CONSTRAINTS;
DROP TABLE Songs CASCADE CONSTRAINTS;
DROP TABLE recorder CASCADE CONSTRAINTS;
DROP TABLE Recordings CASCADE CONSTRAINTS;
